passwd:
  users:
    - name: phillu
      groups:
        - sudo
        - docker
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwNQsxVfRSOHE1qoJ9qEyh0T/7he/RIZXarPWwa6+gswyBjkxqeJlvicnwfFnbByoraB4LnPr3FfCpV97N7wJsr4m2jO3T/XJOaMWw7bKaa6V0apVIAQ2Nd6aBuqRox91I4xvlP1hrIS8IpzQJpyyJaWwVRl93KMJfjugo2G8Y+xjvjaGGA/mGAdJUSf+cVI2AXm2uSj0BWjjbSivh19zIW8ORXEcTprckXrcJT8N6MhownMQ/dOFdxAOLruIzR+uutcEtQK535jd2E4SE26xFr2jJem0E7eY8h0Y7vhyoo9IwCXr6P0lVRzFhSA4wHuWk25/BLvJn3241udqJ4P1J 17:38:92:f2:92:60:dd:41:3e:57:c8:87:64:51:84:99 id_rsa
storage:
  disks:
    - device: /dev/nvme0n1
      wipe_table: true
      partitions:
        - label: ROOT
  filesystems:
    - mount:
        device: /dev/disk/by-partlabel/ROOT
        format: ext4
        wipe_filesystem: true
        label: ROOT
  files:
    - filesystem: root
      path: /opt/secrets.env
      mode: 0755
      contents:
        remote:
          url: tftp://10.0.5.1/env
    - filesystem: root
      path: /home/phillu/.docker/config.json
      mode: 0755
      contents:
        remote:
          url: tftp://10.0.5.1/docker.config.json
systemd:
  units:
    - name: unms.service
      enabled: true
      contents: |
        [Unit]
        Description=unms
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill unms
        ExecStartPre=-/usr/bin/docker rm unms
        ExecStartPre=/usr/bin/docker pull nico640/docker-unms:latest
        ExecStart=/usr/bin/docker run --name unms -p 8080:80 -p 8443:443 -p 2055:2055/udp -e TZ=Europe/Berlin nico640/docker-unms:latest

        [Install]
        WantedBy=multi-user.target