name: build

on:
  push:
    paths:
      - 'boot.ipxe'
      - 'container-linux-config.yaml'
    branches:
      - master

jobs:
  compile-ipxe:
    name: Compile iPXE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout ipxe repo
        uses: actions/checkout@v2
        with:
          repository: 'ipxe/ipxe'
          path: 'ipxe'
          fetch-depth: 0
      - name: Run compile
        run: |
          sudo apt-get install libxml2-utils
          cd ipxe/src
          make bin-x86_64-efi/ipxe.efi EMBED=../../boot.ipxe
      - name: Archive ipxe binary
        uses: actions/upload-artifact@v2
        with:
          name: ipxe.efi
          path: ipxe/src/bin-x86_64-efi/ipxe.efi
      - name: Deploy Files
        run: |
          mv ipxe/src/bin-x86_64-efi/ipxe.efi ipxe.efi
          git config user.name "buildbot"
          git config user.email "buildbot@github.com"
          git add ipxe.efi
          git commit -m "Updated ipxe.efi"
          git push
  transpile-container-linux-config:
    name: Transpile Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Transpile container linux config
        run: |
          chmod +x ct
          cat container-linux-config.yaml | ./ct > ignition.config
      - name: Archive ignition config
        uses: actions/upload-artifact@v2
        with:
          name: ignition.config
          path: ignition.config
      - name: Deploy Files
        run: |
          git config user.name "buildbot"
          git config user.email "buildbot@github.com"
          git add ignition.config
          git commit -m "Updated ignition.config"
          git push