name: build

on: push

jobs:
  compile-ipxe:
    name: Compile iPXE
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout ipxe repo
        uses: actions/checkout@v2
        with:
          repository: 'ipxe/ipxe'
          path: 'ipxe'
          fetch-depth: 0
      - name: Run compile
        run: |
          sudo apt-get install libxml2-utils
          cd ipxe/src
          make bin-x86_64-efi/ipxe.efi EMBED=../../boot.ipxe
      - name: Archive ipxe binary
        uses: actions/upload-artifact@v2
        with:
          name: ipxe
          path: ipxe/src/bin-x86_64-efi/ipxe.efi
  transpile-container-linux-config:
    name: Transpile Config
    runs-on: ubuntu-latest
    steps:
      - name: Transpile container linux config
        run: |
          curl -o ct https://github.com/coreos/container-linux-config-transpiler/releases/download/v0.9.0/ct-v0.9.0-x86_64-unknown-linux-gnu
          chmod +x ct
          cat container-linux-config.yaml | ./ct > ignition.config
      - name: Archive ignition config
        uses: actions/upload-artifact@v2
        with:
          name: ignition
          path: ignition.config

