name: build

on:
  push:
    paths:
      - 'boot.ipxe'
      - 'container-linux-config.yaml'
    branches:
      - master

jobs:
  compile-ipxe:
    name: Compile iPXE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout ipxe repo
        uses: actions/checkout@v2
        with:
          repository: 'ipxe/ipxe'
          path: 'ipxe'
          fetch-depth: 0
      - name: Run compile
        run: |
          sudo apt-get install libxml2-utils
          cd ipxe/src
          make bin-x86_64-efi/ipxe.efi EMBED=../../boot.ipxe
      - name: Archive ipxe binary
        uses: actions/upload-artifact@v2
        with:
          name: ipxe.efi
          path: ipxe/src/bin-x86_64-efi/ipxe.efi
          retention-days: 1
  transpile-container-linux-config:
    name: Transpile Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Transpile container linux config
        run: |
          chmod +x ct
          cat container-linux-config.yaml | ./ct > ignition.config
      - name: Archive ignition config
        uses: actions/upload-artifact@v2
        with:
          name: ignition.config
          path: ignition.config
          retention-days: 1
  upload-artifacts:
    name: Commit artifacts to repository
    needs:
      - transpile-container-linux-config
      - compile-ipxe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        path: artifacts
      - name: Commit and Push files
        run: |
          ls -lah artifacts
          mv artifacts/ignition.config/ignition.config ignition.config
          mv artifacts/ipxe.efi/ipxe.efi ipxe.efi
          git config user.name "buildbot"
          git config user.email "buildbot@github.com"
          git add ipxe.efi ignition.config
          git diff-index --quiet HEAD || git commit -m "Updated ignition.config and/or ipxe.efi"
          git push