name: compile-ipxe

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  compile-ipxe:
    # Name the Job
    name: Compile iPXE
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Checkout ipxe repo
        uses: actions/checkout@v2
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'ipxe/ipxe'
          path: 'ipxe'

      # Runs the Super-Linter action
      - name: Run compile
        run: |
          sudo apt-get install libxml2-utils
          cd ipxe/src
          make bin-x86_64-efi/ipxe.efi EMBED=../../boot.ipxe